### ISSUE TITLE
Asynchronous projections handling.

### ISSUE THREAD

**Issue by lordcysiek** [eventsauce-symfony/eventsauce-bundle#2]
Hello,

Can You share Your vision of asynchronous projections handling?
One of the reasonable solutions is to use Consumer handler to propagate event to async queue as new Command. But it implies some additional artifacts - Consumer -> Command -> Handler for each projection.
I was thinking about centralized, configurable multiple bus propagation for events. Maybe I'm over engineering this?

**Comment by andrew-pakula** [comment]
I am not sure that i correct understood you, but you can use chain dispatchers and if you want to it to be asynchronous, you must use message outbox.

```yaml
framework:
    messenger:
        transports:
            sync: 'sync://'
        buses:
            fooBus:
                default_middleware: allow_no_handlers
            barBus:
                default_middleware: allow_no_handlers
```


```yaml
andreo_event_sauce:
    messenger_message_dispatcher:
        chain:
            foo_dispatcher:
                bus: fooBus # bus alias from messenger config
            bar_dispatcher:
                bus: barBus
    outbox: true
    aggregates:
        foo:
            class: App\Domain\Foo
            outbox: true
```

```php

// projection for foo bus

final class FooProjector implements MessageConsumer, MessageSubscriberInterface
{
    public function __construct(private readonly FooProjectionRepository $fooProjectionRepository)
    {
    }

    public function handle(Message $message): void
    {
        // do something
    }

    public static function getHandledMessages(): iterable
    {
        yield FooCreated::class => [
            'method' => 'handle',
            'bus' => 'fooBus',
        ];
    }
}
```

```php

// projection for bar bus

final class FooProjector implements MessageConsumer, MessageSubscriberInterface
{
    public function __construct(private readonly FooProjectionRepository $fooProjectionRepository)
    {
    }

    public function handle(Message $message): void
    {
        // do something
    }

    public static function getHandledMessages(): iterable
    {
        yield FooCreated::class => [
            'method' => 'handle',
            'bus' => 'barBus',
        ];
    }
}
```
